language: python
python:
  - "3.8"

branches:
  only:
  - master

install:
- pip install -r requirements.txt

script:
- bash generate.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir:
    site/
